<?php

namespace App\DataFixtures;

use App\Entity\Animal;
use App\Entity\Category;
use App\Entity\Cheese;
use App\Entity\Location;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Faker;

class CheeseFixtures extends AbstractFixture implements OrderedFixtureInterface
{

    private $cheeses = [
        "Abondance - AOP",
        "Abbaye de Timadeuc",
        "Abbaye du Mont des Cats",
        "Affidelice au Chablis",
        "Appenzeller",
        "A Casinca",
        "Abbaye de Citeaux",
        "Abbaye de Tamié",
        "Anneau Du Vic-Bilh",
        "Ardi-Gasna",
        "Aveyronnais",
        "Boulette d'Avesnes",
        "Brebichou au Thym",
        "Burrata des Pouilles",
        "Brie aux truffes",
        "Briquette de Brebis",
        "Banon",
        "Beaufort - AOP -",
        "Bel Fiuritu",
        "Bethmale",
        "Bichon",
        "Bleu d'Auvergne",
        "Bleu de Gex",
        "Bleu de Laqueuille",
        "Bleu de Sassenage",
        "Bleu de Severac",
        "Bleu des Causses",
        "Bôfavre",
        "Bondon à la Fleur de Sel",
        "Bouchons de chèvre",
        "Boulette d'Avesnes blanche",
        "Bouton d'Oc",
        "Boutons de Culotte",
        "Bouyguette",
        "Bouyssou",
        "Brebis du Lavort",
        "Brebis du Lochois",
        "Brescianella",
        "Brie au Poivre",
        "Brie de Meaux",
        "Brie de Melun",
        "Brillat aux truffes",
        "Brillat Savarin",
        "Brin d'Amour",
        "Brique Cendrée",
        "Brique de Chèvre",
        "Briquette du Forez",
        "Briquette du Nord",
        "Broccio Passu",
        "Brossauthym",
        "Brousse de Brebis",
        "Buchette cendrée sec",
        "Coulommiers",
        "Clacbitou",
        "Coulommiers aux Truffes",
        "Cabri de Parthenay",
        "Cathare",
        "Cabécou",
        "Cabriolu",
        "Cabrioulet au piment d'Espelette",
        "Calisson",
        "Camembert au Calvados",
        "Camembert de Normandie AOP",
        "Cancoillotte Nature",
        "Cancoillotteau vin jaune",
        "Cantal Entre Deux",
        "Cap Gris Nez",
        "Carré Corse",
        "Carré d'Ambre",
        "Carré du Tarn",
        "Carré du Vinage",
        "Carré Mirabelle",
        "Carré Normand",
        "Cavet Feuille",
        "Cendre d'Olivet",
        "Cendré du Beauzac",
        "Chabichou du Poitou",
        "Chabichou du Poitou sec",
        "Chabis",
        "Chambertin",
        "Chaource",
        "Charolais",
        "Cheddar",
        "Cheddar barre",
        "Chèvre des Gors",
        "Chèvre Figue à la Rose",
        "Chevrotin des Aravis",
        "Coeur d'Arras",
        "Coeur de Chevre",
        "Coeur de France",
        "Coeur de Neufchâtel",
        "Coeur de Touraine blanc",
        "Coeur de Touraine cendré",
        "Coeur et Creme",
        "Comté",
        "Coquillon",
        "Couronne de Melle",
        "Couronne des 3 Seigneurs",
        "Couronne Lochoise",
        "Crémeux du Jura",
        "Croix Occitane",
        "Crottin",
        "Crottin - Pays Fort",
        "Crottin de brebis",
        "Crottin deux affinages",
        "Crottin sec",
        "Crottin sec à l'huile d'olive",
        "Curé Nantais",
        "Dauphin",
        "Délice des Fiouves",
        "Délice du Poitou",
        "Ecir de l'Aubrac",
        "Echourgnac à la liqueur de noix",
        "Elgines",
        "Emmental Grand Cru",
        "Enrobé aux Airelles",
        "Enrobé aux Poivres",
        "Enrobé aux Raisins",
        "Enrobé du Soleil",
        "Entrammes",
        "Epoisses de Bourgogne",
        "Espi du Poitou",
        "Fleur du Maquis",
        "Fumaison",
        "Figuette aux Epices",
        "Filetta Corse",
        "Fior di Capra",
        "Fior di Pecura",
        "Fiore di Muntagna",
        "Fiore Dolce",
        "Fiore Sardo",
        "Fiumorbù",
        "Fleury",
        "Fondant de Brebis",
        "Fontina",
        "Fougerus",
        "Fourme d'Ambert",
        "Fourme d'Ambert affinée au Vouvray",
        "Fourme de Haute Loire",
        "Fourme de Montbrison",
        "Fourme de Rochefort",
        "Fribourg",
        "Gaperon",
        "Gouda",
        "Galette des Templiers",
        "Galette Lyonnaise",
        "Galletout",
        "Gorgonzola Dolce",
        "Gorgonzola Piccante",
        "Gouda au cumin",
        "Gouda aux épices",
        "Gouda de chèvre",
        "Gour Noir",
        "Goutte du Limousin",
        "Grana Padano",
        "Grand Munster",
        "Gratte-Paille",
        "Grés des Vosges",
        "Gruyere Suisse",
        "Gruyère Suisse",
        "L'Encalat",
        "La Basquaise",
        "La fondue savoyarde",
        "La Marotte",
        "Laguiole",
        "Langres",
        "Le Baraillan",
        "Le Figou",
        "Le Galet de Thomas",
        "Le Guérandais",
        "Le Mellois",
        "Le Pipoune",
        "Le Pipoune affiné",
        "Le Roumé",
        "Le Trèfle",
        "Lechatolet",
        "Lingot du Berger",
        "Lingot Saint Bousquet d Orb",
        "Livarot",
        "Lorenthym",
        "Losange",
        "Lossaba",
        "Lou Pevre",
        "Lou Rocaillou",
        "Lou Sarriette",
        "Mont ventoux",
        "Machecoulais",
        "Maconnais",
        "Malvault",
        "Manchego",
        "Manchego et Miel",
        "Maroilles",
        "Mascare",
        "Massadel",
        "Mimolette jeune",
        "Mimolette vieille",
        "Miniclac",
        "Moelleux du Revard",
        "Montbriac",
        "Montrachet",
        "Morbier",
        "Morbier 100 jours",
        "Mothais sur Feuille",
        "Moulis",
        "Munster",
        "Munster au Cumin",
        "Murol",
        "Olivia Provence",
        "Olivet à la Sauge",
        "Olivet au Poivre",
        "Olivet Cendré",
        "Ossau-Iraty",
        "Ovale de Chèvre",
        "Ovalie",
        "Pont l'Evêque",
        "Pecorino Siciliano Pepato",
        "Persillé de Tignes",
        "Pictou",
        "Palet de Bourgogne",
        "Palet du Maursois",
        "Parmigiano Reggiano",
        "Pas de l'Escalette",
        "Patte d'Ours",
        "Pave Blesois",
        "Pave d'Aremberg",
        "Pavé de Betz",
        "Pavé de Maizières",
        "Pavé du Berry",
        "Pavé du Larzac",
        "Pe Descaous",
        "Pecurinu",
        "Pelardon",
        "Perail de Brebis",
        "Persillé de chèvre",
        "Persille du mont-Blanc",
        "Petit Morin",
        "Petit Perche",
        "Petit Pont l'Evêque",
        "Petit Tröo",
        "Piastrellou",
        "Pic",
        "Picodon",
        "Pisé du Lot",
        "Plaisir au Chablis",
        "Poiti'Rond sec",
        "Pont d'Yeu",
        "Pougne Cendré",
        "Pouligny Saint-Pierre",
        "Pyrénées de Brebis",
        "Queijo do Pastor",
        "Rovethym",
        "Raclette Ail des Ours",
        "Raclette de Savoie",
        "Raclette de Savoie fumée",
        "Raclette Suisse",
        "Reblochon - AOP -",
        "Regal de Bourgogne",
        "Rigotte de Condrieu",
        "Rocamadour",
        "Romans Part Dieu",
        "Romarin",
        "Rondin du Nord",
        "Roquefort",
        "Roquefort Carles",
        "Rouelle",
        "Rouleau de Beaulieu",
        "Rouleau de Provence",
        "Rove des Garrigues",
        "Saint Nicolas de la Dalmerie",
        "Sablé du Boulonnais",
        "Saint Domnin",
        "Saint Felicien",
        "Saint Marcellin",
        "Saint Nectaire",
        "Saint Paulin",
        "Saint Point",
        "Saint Romans",
        "Saint Valentin",
        "Saint Vincent au Chablis",
        "Sainte Maure de Touraine",
        "Salers",
        "Sancerre",
        "Saulzais",
        "Selles sur Cher",
        "Six Pans du Lauragais",
        "Soumaintrain",
        "Stilton",
        "Taupinette",
        "Taleggio",
        "Tomme Crayeuse",
        "Tomme Morgée à la bière et au houblon",
        "Tomme Grise de Chèvre",
        "Tête de Moine",
        "Tome à la Sarriette",
        "Tome de Provence",
        "Tomette à l'huile",
        "Tomme Brulee",
        "Tomme Corse",
        "Tomme d'Accous",
        "Tomme d'Auvergne",
        "Tomme de Belloc",
        "Tomme de Lozère",
        "Tomme de Savoie - IGP -",
        "Tomme de Yenne",
        "Tomme du Jura",
        "Tomme Estaing",
        "Tomme Marc de Raisin",
        "Tomme Pierucci",
        "Tommette d'Espelette",
        "Tommette de Corbières",
        "Tommette de Yenne",
        "Tommette du Tarn",
        "Tommette Laious",
        "Toudeille Chèvre-Brebis",
        "Triangle saillot",
        "Trifulin",
        "Trio de Camembert",
        "Trio des Montagnes",
        "Trou du Cru",
        "Truffe de Valensole",
        "Truffe du Perigord",
        "Valencay",
        "Vacherin - Mont d'Or",
        "Vacherin Suisse",
        "Venaco",
        "Vieux Lille",
        "Voeu du Poitou",
    ];

    public function load(ObjectManager $manager)
    {

        $faker = Faker\Factory::create('fr_FR');

        $categories = $manager->getRepository(Category::class)->findAll();
        $locations = $manager->getRepository(Location::class)->findAll();
        $animals = $manager->getRepository(Animal::class)->findAll();

        foreach ($this->cheeses as $value) {
            $cheese = new Cheese();
            $cheese->setName($value);
            $cheese->setDescription($faker->text);

            $category = $categories[array_rand($categories, 1)];
            $location = $locations[array_rand($locations, 1)];
            $animal = $animals[array_rand($animals, 1)];

            $cheese->setCategory($category);
            $cheese->setLocation($location);
            $cheese->setAnimal($animal);

            $manager->persist($cheese);
        }

        $manager->flush();
    }

    public function getDependencies()
    {
        return [
            'App\DataFixtures\CategoryFixtures',
            'App\DataFixtures\LocationFixtures',
            'App\DataFixtures\AnimalFixtures',
            ];
    }

    /**
     * Get the order of this fixture
     *
     * @return integer
     */
    public function getOrder()
    {
        return 6;
    }
}