<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.U56v430' shared service.

return $this->privates['.service_locator.U56v430'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('clientRegistry' => function () {
    return ($this->services['knpu.oauth2.registry'] ?? $this->services['knpu.oauth2.registry'] = new \KnpU\OAuth2ClientBundle\Client\ClientRegistry($this, array('google' => 'knpu.oauth2.client.google', 'facebook' => 'knpu.oauth2.client.facebook')));
}));
