version: '2'

services:
    db:
        image: postgres:10.1
        restart: always
        environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
        - 5432:5432
        volumes:
        - ./conf/postgres/:/docker-entrypoint-initdb.d/
    php:
        build:
            context: conf/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build:
            context: conf/nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    mailhog:
        image: mailhog/mailhog
        ports:
        - 1025:1025 # smtp server
        - 8025:8025 # web ui