<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ0AmjFO\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ0AmjFO/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJ0AmjFO.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJ0AmjFO\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJ0AmjFO\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'J0AmjFO',
    'container.build_id' => 'c4aa6bcc',
    'container.build_time' => 1538744707,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ0AmjFO');
