<?php

namespace App\Repository;

use App\Entity\Cheese;
use App\Entity\UsersCheesesRatings;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * @method Cheese|null find($id, $lockMode = null, $lockVersion = null)
 * @method Cheese|null findOneBy(array $criteria, array $orderBy = null)
 * @method Cheese[]    findAll()
 * @method Cheese[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class CheeseRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Cheese::class);
    }

    //@TODO Shall not Change
    public function cheeseOfTheWeek(): ?Cheese
    {
        $cheese = $this->findOneBy([], []);
        return $cheese;
    }

    public function search($name)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT c, l, p, ca, a
            FROM App\Entity\Cheese c
            JOIN c.location l
            JOIN l.country p
            JOIN c.category ca
            JOIN c.animal a
            WHERE LOWER(c.name) LIKE :name
        ');

        $query->setParameter('name', '%' . mb_strtolower($name) . '%');
        $query->execute();
        return $query->getArrayResult();
    }

    public function count(array $criteria)
    {
        return parent::count($criteria); // TODO: Change the autogenerated stub
    }

    public function globalRating(Cheese $cheese): float
    {
        $usersCheesesRatings = $this->getEntityManager()->getRepository(UsersCheesesRatings::class)->findBy(['cheese' => $cheese]);
        $globalRating = 0;
        foreach ($usersCheesesRatings as $rating){
            $globalRating += $rating->getRating()->getMark();
        }
        $globalRating = $globalRating / count($usersCheesesRatings);
        return $globalRating;
    }
}
