easy_admin:
  entities:
    Category:
      class: App\Entity\Category
      label: 'Categories'
      list:
        fields:
        - id
        - name
        - description
      show:
        fields:
        - id
        - name
        - description
      form:
        fields:
        - { type: 'group', css_class: 'col', label: 'Basic information', icon: 'pencil' }
        - { property: 'name', css_class: 'large' }
        - { property: 'description' }