# This file sets the configuration of the 'Product' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
  entities:
    # the configuration of this entity is very verbose because it's used as
    # an example to show all the configuration options available for entities
    # check out the configuration of the other entities to see how concise
    # can be the configuration of your backend
    User:
      class: App\Entity\User
      label: 'Users'
      list:
        fields:
        - id
        - fullname
        - username
        - email
        - password
        - roles
        - validate
        - created_at
      show:
        fields:
        - id
        - fullname
        - username
        - email
        - password
        - roles
        - validate
        - created_at
      form:
        fields:
        - { type: 'group', css_class: 'col-sm-8', label: 'Basics informations', icon: 'pencil' }
        - { property: 'fullname' }
        - { property: 'username' }
        - { type: 'divider' }
        - { property: 'email' }
        - { type: 'group', css_class: 'col-sm-4', label: 'Privates informations', icon: 'cube' }
        - { property: 'password', type: 'password' }
        - { type: 'group', label: 'Advanced Settings', icon: 'warning' }
#        - { property: 'roles' }
        - { property: 'validate'}
        - { property: 'created_at'}
